services:
  goodmem-mcp:
    build: .
    container_name: goodmem-mcp-server
    environment:
      # Since we're on the same network, we can use the container name directly
      - GOODMEM_API_URL=${GOODMEM_API_URL:-http://goodmem-server:8080}
      - GOODMEM_API_KEY=${GOODMEM_API_KEY}
      - GOODMEM_DEFAULT_SPACE=${GOODMEM_DEFAULT_SPACE:-default}
      - LOG_LEVEL=${LOG_LEVEL:-info}
    networks:
      - goodmem_default
    restart: unless-stopped
    stdin_open: true
    tty: true
    command: node dist/index.js

networks:
  goodmem_default:
    external: true