version: '3.8'

services:
  goodmem-mcp:
    build: .
    container_name: goodmem-mcp-server
    environment:
      # Since both containers are on same host, use the container name
      - GOODMEM_API_URL=http://goodmem-server:8080
      - GOODMEM_API_KEY=${GOODMEM_API_KEY}
      - GOODMEM_DEFAULT_SPACE=${GOODMEM_DEFAULT_SPACE:-default}
      - LOG_LEVEL=${LOG_LEVEL:-info}
    networks:
      - goodmem-network
    restart: unless-stopped
    stdin_open: true
    tty: true
    # MCP uses stdio, so we need to keep the container running
    command: node dist/index.js

# Connect to the existing Goodmem network
networks:
  goodmem-network:
    external: true
    name: bridge  # Docker's default bridge network